name: run paimon spark deploy

triggers:
  schedule:
    - cron: "0 6 * * 1"
      branches:
        - "emr/esr-master"

jobs:
  deploy:
    name: 部署 paimon 到 emr-release

    timeout: 2h

    image: 'crpi-ikefsbzah0txoyw5.cn-hangzhou.personal.cr.aliyuncs.com/emr-ss/spark:20250813-1-amd'

    steps:
      - id: fetch-image
        container:
          credentials:
            username: ${{vars.docker_username}}
            password: ${{secrets.docker_password}}
        run: "echo 'fetch image'"

      - id: checkout-paimon
        uses: checkout
        inputs:
          repository-url: 'git@gitlab.alibaba-inc.com:soe/emr-paimon.git'
          ref: ${{git.commitId}}
          path: 'paimon'
          username: ${{vars.code_username}}
          token: ${{secrets.code_token}}

      - id: run-deploy
        run: |
          # common env
          set -ex
          export WORKSPACE=$(pwd)

          # job args
          export SS_MAVEN_USERNAME=${{vars.ss_maven_username}}
          export SS_MAVEN_PASSWORD=${{secrets.ss_maven_password}}

          echo "start run deploy"
          sh ${WORKSPACE}/paimon/.aoneci/shell/deploy.sh
          echo "finish run deploy"
